name: Send Open Prices

on:
  workflow_dispatch:    # 수동 실행 버튼 활성화
  schedule:
    - cron: '0 23 * * *'  # 매일 23:00 UTC → 다음날 08:00 KST

jobs:
  send-open:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyupbit requests

      - name: Run ai.py
        run: python ai.py
